# Numpy Arrays

NumPy (or Numpy) is a Linear Algebra Library for Python.

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

## Vectors

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.21957452, 0.0226896 , 0.98549824, 0.00857192, 0.2792885 ])

In [15]:
np.random.rand(5,5)

array([[0.37058675, 0.79856816, 0.34363005, 0.95273984, 0.32265169],
       [0.33167996, 0.38263761, 0.50366976, 0.46378033, 0.71716801],
       [0.93782867, 0.85663386, 0.46151228, 0.16617517, 0.98188708],
       [0.92044815, 0.50095604, 0.6298235 , 0.344602  , 0.20097715],
       [0.43578287, 0.96449209, 0.50672942, 0.01631754, 0.60485859]])

In [16]:
np.random.randn(4,4)

array([[ 0.53072697, -0.41986558, -0.68457738,  0.6756967 ],
       [-0.06369012, -0.16858581, -0.33975314, -0.54027708],
       [-0.16882727, -0.21978545, -0.25619985,  0.0616346 ],
       [-1.58512222, -0.28360568, -1.89061708, -0.58961075]])

In [17]:
np.random.randint(1,100,10)

array([37, 78, 53, 80, 85, 29, 44, 90, 57, 15])

In [18]:
arr = np.arange(25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr = np.random.randint(0,50,10)

In [21]:
ranarr

array([36, 36, 47, 37, 29, 24, 26, 17, 27,  1])

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
ranarr.max()

47

In [24]:
ranarr.min()

1

In [25]:
ranarr.argmax()

2

In [26]:
ranarr.argmin()

9

In [27]:
arr = arr.reshape(5,5)

In [28]:
arr.shape

(5, 5)

In [29]:
arr.dtype

dtype('int32')

In [30]:
from numpy.random import randint

In [31]:
randint(2,10)

4

In [32]:
arr = np.arange(0,11)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr[8]

8

In [35]:
arr[1:5]

array([1, 2, 3, 4])

In [36]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [37]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [38]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
arr[0:5] = 100

In [40]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [41]:
arr = np.arange(0,11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
slice_of_arr = arr[0:6]

In [44]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [45]:
slice_of_arr[:] = 99

In [46]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
arr_copy = arr.copy()

In [48]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [50]:
arr_copy[:] = 100

In [51]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [52]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Matrices

In [54]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [56]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
arr_2d[0]

array([ 5, 10, 15])

In [60]:
arr_2d[2,1]

40

In [62]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [69]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [70]:
arr = np.arange(1,11)

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
bool_arr = arr > 5

In [74]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [75]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [76]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [77]:
arr[arr<3]

array([1, 2])

In [78]:
arr_2d = np.arange(50).reshape(5,10)

In [79]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [80]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [81]:
arr = np.arange(11)

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [84]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [85]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [86]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [88]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [89]:
arr // 2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5], dtype=int32)

In [92]:
1 / arr

<ipython-input-92-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [93]:
arr / arr

<ipython-input-93-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [94]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [95]:
arr ** arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [96]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [98]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [99]:
np.max(arr)

10

In [100]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [101]:
np.log(arr)

<ipython-input-101-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])