# Numpy Arrays

NumPy (or Numpy) is a Linear Algebra Library for Python.

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

In [3]:
import numpy as np

In [4]:
my_list = [1,2,3]

In [6]:
my_list

[1, 2, 3]

In [7]:
arr = np.array(my_list)

In [13]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.random.rand(5)

array([0.53372156, 0.95279632, 0.83880018, 0.87325274, 0.63456905])

In [31]:
np.random.rand(5,5)

array([[0.14030429, 0.36787939, 0.33432636, 0.58622982, 0.13235147],
       [0.32705765, 0.44641956, 0.37918849, 0.91509108, 0.38917956],
       [0.82947318, 0.11802476, 0.54378383, 0.44432309, 0.87706552],
       [0.93905846, 0.97015318, 0.23144239, 0.69622252, 0.82487958],
       [0.25549851, 0.90670513, 0.50601513, 0.01820488, 0.1999433 ]])

In [33]:
np.random.randn(4,4)

array([[-1.01576787, -0.06664406,  0.22536419,  0.968483  ],
       [-0.21817044, -0.62038853,  1.3074212 , -0.39032419],
       [ 1.52593188, -1.47559587,  0.15249495,  0.29208379],
       [-0.55863006, -0.26409047, -0.3261288 , -1.03257794]])

In [49]:
np.random.randint(1,100,10)

array([85, 29, 37, 68, 19, 76, 28, 90, 24, 51])

In [50]:
arr = np.arange(25)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
ranarr = np.random.randint(0,50,10)

In [53]:
ranarr

array([37, 18, 34, 37, 28, 41,  3, 13, 13, 11])

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
ranarr.max()

41

In [57]:
ranarr.min()

3

In [58]:
ranarr.argmax()

5

In [59]:
ranarr.argmin()

6

In [64]:
arr = arr.reshape(5,5)

In [65]:
arr.shape

(5, 5)

In [66]:
arr.dtype

dtype('int32')

In [67]:
from numpy.random import randint

In [68]:
randint(2,10)

5